--[[
       Copyright © 2025 Davi PEIXELAS
       Licensed under the MIT License.
       See LICENSE file in the project root for full license text.
       
       Offset-finder.lua
        built and generated by: PEIXE
   https://discord.gg/N49fmtT3VZ  -community
--]]

io = require"io"
getModuleProcesAddress = function(modulo)
  for linha in io:lines"/proc/self/maps" do
    local a = linha:match"^(%x+)-"
    if a and linha:find(modulo,1, true) then 
      return tonumber(a, 16)
    end
  end
end



